version: '3.8'  # Puedes usar cualquier versión compatible con Docker Compose

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_remote360
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
